apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-vs
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/hello-gateway
  http:
  - match:
    - uri:
        exact: "/web"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: web-front-end.rest-api-with-mesh.svc.cluster.local
  - match:
    - uri:
        exact: "/web/hello"
    rewrite:
      uri: "/hello"
    route:
    - destination:
        host: web-front-end.rest-api-with-mesh.svc.cluster.local
  - match:
    - uri:
        exact: "/web/hello-service"
    rewrite:
      uri: "/hello-service"
    route:
    - destination:
        host: web-front-end.rest-api-with-mesh.svc.cluster.local
